version: "3"
services:
  react:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: learning-drops_container
    tty: true
    volumes:
      - ./:/app/react
    command: sh -c "cd /app/react  && yarn start"
    ports:
      - 3000:3000
